#!/usr/bin/env bun

import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";

const target = resolve(process.argv[2] ?? "my-vyline-plugin");
const pluginName = sanitize(basename(target));

if (existsSync(target)) {
  console.error(`Target already exists: ${target}`);
  process.exit(1);
}

await mkdir(`${target}/src`, { recursive: true });

await writeFile(
  `${target}/package.json`,
  json({
    name: pluginName,
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: {
      dev: "bun src/index.ts",
      typecheck:
        "bun -e \"const source=await Bun.file('src/index.ts').text(); new Bun.Transpiler({ loader: 'ts', target: 'bun' }).transformSync(source)\"",
    },
    dependencies: {
      "@vyline/plugin-sdk": "workspace:*",
    },
  }),
);

await writeFile(
  `${target}/vyline.plugin.json`,
  json({
    id: pluginName,
    name: title(pluginName),
    version: "0.1.0",
    entry: "./src/index.ts",
    permissions: ["messages:read"],
    description: "A Vyline plugin.",
  }),
);

await writeFile(
  `${target}/src/index.ts`,
  `type VylinePluginContext = {
  logger?: {
    info: (...args: unknown[]) => void;
    warn: (...args: unknown[]) => void;
    error: (...args: unknown[]) => void;
  };
};

export default {
  id: "${pluginName}",
  name: "${title(pluginName)}",
  version: "0.1.0",
  permissions: ["messages:read"],
  async activate(context: VylinePluginContext) {
    context.logger?.info("${pluginName} activated");
  },
  async deactivate(context: VylinePluginContext) {
    context.logger?.info("${pluginName} deactivated");
  },
};
`,
);

await writeFile(
  `${target}/README.md`,
  `# ${title(pluginName)}

Vyline plugin generated by \`vyl plugin create\`.

## Development

\`\`\`bash
bun install
bun run typecheck
\`\`\`

## Manifest

Edit \`vyline.plugin.json\` to declare plugin metadata and permissions.
`,
);

console.log(`Created Vyline plugin template: ${target}`);

function json(value: unknown) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function sanitize(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "") || "vyline-plugin"
  );
}

function title(value: string) {
  return value
    .split(/[._-]+/g)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}
