import type { Chat, Message, SelfProfile, Settings } from "@/lib/store-types";

const now = Date.now();

export const demoSelf: SelfProfile = {
  name: "デモユーザー",
  avatar: "D",
  status: "Vylineを体験中",
  mid: "demo-self",
};

export const demoChats: Chat[] = [
  {
    id: "demo-chat-team",
    type: "group",
    name: "Vyline開発チーム",
    avatar: "V",
    color: "#6d5dfc",
    status: "3人のメンバー",
    online: true,
    members: [
      { id: "demo-alice", name: "あおい", avatar: "A", color: "#f59e0b" },
      { id: "demo-bob", name: "れん", avatar: "R", color: "#10b981" },
      { id: "demo-self", name: "デモユーザー", avatar: "D", color: "#6d5dfc" },
    ],
    unread: 2,
    pinned: true,
    lastMessagePreview: "新しいテーマを確認しました",
    lastMessageTime: now,
  },
  {
    id: "demo-chat-gallery",
    type: "group",
    name: "機能ギャラリー",
    avatar: "G",
    color: "#8b5cf6",
    status: "メディア・Flex・通話履歴",
    online: true,
    members: [
      { id: "demo-alice", name: "あおい", avatar: "A", color: "#f59e0b" },
      { id: "demo-self", name: "デモユーザー", avatar: "D", color: "#6d5dfc" },
    ],
    unread: 0,
    lastMessagePreview: "すべて仮データで表示しています",
    lastMessageTime: now - 30_000,
  },
  {
    id: "demo-chat-support",
    type: "friend",
    name: "サンプルサポート",
    avatar: "S",
    color: "#0ea5e9",
    status: "いつでもどうぞ",
    online: true,
    unread: 0,
    lastMessagePreview: "ヘルプを表示できます",
    lastMessageTime: now - 60_000,
  },
  {
    id: "demo-chat-official",
    type: "friend",
    name: "Vylineニュース",
    avatar: "N",
    color: "#06c755",
    status: "公式アカウントの表示例",
    isOfficial: true,
    unread: 1,
    lastMessagePreview: "アップデート情報をお届けします",
    lastMessageTime: now - 90_000,
  },
  {
    id: "demo-chat-memo",
    type: "friend",
    name: "自分用メモ",
    avatar: "M",
    color: "#ec4899",
    status: "端末内のデモデータ",
    isSelf: true,
    unread: 0,
    lastMessagePreview: "ここは仮のチャットです",
    lastMessageTime: now - 120_000,
  },
];

export const demoMessages: Message[] = [
  {
    id: "demo-message-1",
    chatId: "demo-chat-team",
    authorId: "demo-alice",
    kind: "text",
    text: "これは撮影用の仮メッセージです。実アカウントとは接続していません。",
    createdAt: now - 180_000,
    status: "read",
    read: true,
    messageState: "normal",
    readBy: ["demo-alice", "demo-bob"],
  },
  {
    id: "demo-message-2",
    chatId: "demo-chat-team",
    authorId: "me",
    kind: "text",
    text: "検索、返信、スタンプ、テーマ変更などを実際のUIで操作できます。",
    createdAt: now - 120_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-message-3",
    chatId: "demo-chat-team",
    authorId: "demo-bob",
    kind: "sticker",
    sticker: "/demo/sticker-heart.svg",
    altText: "デモスタンプ",
    createdAt: now - 60_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-message-4",
    chatId: "demo-chat-team",
    authorId: "me",
    kind: "text",
    text: "個人情報を含まない安全なPRデモです。",
    createdAt: now - 20_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-image",
    chatId: "demo-chat-gallery",
    authorId: "demo-alice",
    kind: "image",
    imageSrc: "/demo/chat-photo.svg",
    createdAt: now - 420_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-audio",
    chatId: "demo-chat-gallery",
    authorId: "demo-alice",
    kind: "audio",
    audioSeconds: 12,
    createdAt: now - 360_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-file",
    chatId: "demo-chat-gallery",
    authorId: "me",
    kind: "file",
    file: { name: "Vyline-デモ資料.pdf", size: 2_480_000 },
    createdAt: now - 300_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-location",
    chatId: "demo-chat-gallery",
    authorId: "demo-alice",
    kind: "location",
    location: {
      title: "デモ会場",
      address: "サンプル区デモ通り 1-2-3",
      latitude: 35.681236,
      longitude: 139.767125,
    },
    createdAt: now - 240_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-flex",
    chatId: "demo-chat-gallery",
    authorId: "demo-alice",
    kind: "flex",
    altText: "Vylineの機能紹介カード",
    flexJson: {
      type: "bubble",
      body: {
        type: "box",
        layout: "vertical",
        spacing: "md",
        contents: [
          { type: "text", text: "Vyline", weight: "bold", size: "xl", color: "#6d5dfc" },
          { type: "text", text: "LINEをもっと自分らしく", wrap: true, color: "#444444" },
          { type: "separator", color: "#dddddd" },
          { type: "text", text: "テーマ・返信・メディア・バックアップ", wrap: true, size: "sm" },
        ],
      },
      footer: {
        type: "box",
        layout: "vertical",
        contents: [
          {
            type: "button",
            style: "primary",
            action: { type: "message", label: "詳しく見る", text: "Vylineの機能を見せて" },
          },
        ],
      },
    },
    createdAt: now - 180_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-call",
    chatId: "demo-chat-gallery",
    authorId: "me",
    kind: "call",
    callMeta: { video: true, group: true, durationSec: 185, outcome: "ended" },
    createdAt: now - 120_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-system",
    chatId: "demo-chat-gallery",
    authorId: "demo-alice",
    kind: "system",
    text: "あおいがアナウンスを更新しました",
    createdAt: now - 60_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
  {
    id: "demo-gallery-caption",
    chatId: "demo-chat-gallery",
    authorId: "me",
    kind: "text",
    text: "すべて撮影用の仮データです。実アカウントには接続しません。",
    createdAt: now - 20_000,
    status: "read",
    read: true,
    messageState: "normal",
  },
];

export const demoSettings: Settings = {
  animationMode: "vyline",
  readReceipts: true,
  showReaderList: true,
  streamerMode: true,
  compactDensity: false,
  fontScale: 1,
  enterToSend: true,
  alwaysMuteMessages: false,
  voiceMessagesEnabled: true,
  chatSort: "recent",
  bubbleTail: true,
  showStatusMessage: true,
  showBackground: false,
  highQualityImages: false,
  proxyEnabled: false,
  proxyUrl: "",
  notificationsEnabled: true,
  betaBlockCheckManual: false,
  betaBlockCheckAuto: false,
  betaMidSearch: false,
  betaAgentI: false,
};
